const swaggerAutogen = require('swagger-autogen')()
require("dotenv").config();


const doc = {
    info: {
        version: "1.0.0",
        title: "Retrieving Weathere Forecast data using openweathermap.",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: process.env.IP_ADDRESS + ":" + process.env.PORT,
    basePath: "/",
    schemes: ['http','https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [{
        "name": "Weather Forecast",
        "description": "Endpoints"
    }],
    // securityDefinitions: {
    //     AUTHORIZATION: {
    //         type: "apiKey",
    //         name: "appid",
    //         in: "query",
    //         description: "Enter JWT Bearer token **_only_**",
    //         scheme: "bearer",
    //         bearerFormat: "JWT"
    //     },
    //     security: [
    //         {
    //             AUTHORIZATION: []
    //         }
    //     ],
    // },
    definitions: {     
            getWeatherData: {
                q: "name of the city",
            }
        }

}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./index.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index') // Your project's root file
})